import type { IconType } from 'react-icons';
import {
  SiBlender,
  SiBootstrap,
  SiClaude,
  SiCss,
  SiFigma,
  SiFirebase,
  SiGit,
  SiGooglegemini,
  SiGithub,
  SiGithubcopilot,
  SiHtml5,
  SiJavascript,
  SiNodedotjs,
  SiPostgresql,
  SiPython,
  SiReact,
  SiSupabase,
  SiTypescript,
  SiUnity,
  SiVite,
} from 'react-icons/si';
import { VscCode, VscDatabase, VscSparkle, VscVscode } from 'react-icons/vsc';
import type { TechnologyIconKey } from '../../data/technologiesData';

export const technologyIconMap = {
  html: SiHtml5,
  css: SiCss,
  javascript: SiJavascript,
  typescript: SiTypescript,
  react: SiReact,
  vite: SiVite,
  bootstrap: SiBootstrap,
  firebase: SiFirebase,
  sql: VscDatabase,
  postgresql: SiPostgresql,
  supabase: SiSupabase,
  nodejs: SiNodedotjs,
  git: SiGit,
  github: SiGithub,
  figma: SiFigma,
  unity: SiUnity,
  blender: SiBlender,
  python: SiPython,
  'visual-studio-code': VscVscode,
  chatgpt: VscSparkle,
  claude: SiClaude,
  gemini: SiGooglegemini,
  codex: VscCode,
  'github-copilot': SiGithubcopilot,
} satisfies Record<TechnologyIconKey, IconType>;
